### PR TITLE
Allow RequestHandler* to return subclasses of Response

### PR DESCRIPTION
**Pull request by aantoniadis**

### CODE REVIEW

**Comment by aantoniadis** [comment]
@aleixmorgadas the purpose of this PR is to have some code as a reference for our discussion. As soon as we conclude on the API, I can update the docs and the vlingo modules that use it.

**Comment by aleixmorgadas** [comment]
> @aleixmorgadas the purpose of this PR is to have some code as a reference for our discussion. As soon as we conclude on the API, I can update the docs and the vlingo modules that use it.

OK! BTW, GitHub introduced the [Draft PullRequests](https://github.blog/2019-02-14-introducing-draft-pull-requests) last month, so useful to mark a PR as work in progress.

Which are the minimum next steps to merge the PR in your opinion? I see this as a on-going improvement, we can do a more patch on top of this one. The best way to know how an API works is using it, since @kmruiz and I are doing a web server with vlingo, we'll test the new published design there and provide feedback later.

As you have seen, the last PR we merged got a conflict on your PR, tomorrow I'll find some time to fix the conflict.

On the other hand, you might like to join our [Gitter](https://gitter.im/vlingo-platform-java/http).

**Comment by aantoniadis** [comment]
@aleixmorgadas I think that we need to find a better way to handle the errors. I don't really like the wrap/unwrap that has to be done to make error `Response`s look like `Throwable`s

**Comment by aleixmorgadas** [comment]
> @aleixmorgadas  I think that we need to find a better way to handle the errors. I don't  really like the wrap/unwrap that has to be done to make error Responses look like Throwables

I do agree here, we should have a better way.

Let me drop an idea, is a 404 an Error or an expected behaviour? When we create the API, we model some 4XX & 5XX errors as expected behaviour, that _Responses_ should be part of `Outcome<?, Response>` or `Outcome<ErroredResponse, ?>`??.

We have 3 situations:

- Expected value of an Actor Method `Outcome<?,SuccessType>` maps to `Outcome<?, SuccessResponse>`
- Expected exception of an Actor Method `Outcome<ErrorType,?>` maps to `Outcome<?, ErroredResponseButExpected>`
- Unexpected exception of an Actor Method `Outcome<NPE, ?>` maps to `Outcome<UnhandledException,?>` (it's handled by ResourceHandler to map into 5XX Response)

Does it make sense?

I don't mind give more freedom in the `Outcome` to not force do the `wrap/unwrap`

**Comment by aantoniadis** [comment]
@aleixmorgadas I would say that 404 is closer to the absence of an Optional so it is expected. `Future`s, `Either`s `Optional`s etc are used to [capture effects](https://www.youtube.com/watch?v=sTSQlYX5DU0), so I think that the question we have to answer is which of these effects are valuable for the consumer of these APIs.

The purpose of the issue is to have the subtype of the (normal) response in APIs but we have to avoid making the consumers complex. Combining Future, Either and Try would be more expressive but would make the API hard to use.

`Completes` should stay as part of the API but for the errors, I believe that following the `Either` approach would be simpler. An alternative would be to model all errors (expected or not) as exceptions and use `Outcome` which is similar to `Try`. 

Keep in mind that `Supplier<Completes<T>> executeAction` also needs to change to adapt to the new API. Alternatively, we could map the result of this supplier accordingly.

What do you think?

**Comment by aleixmorgadas** [comment]
> Completes should stay as part of the API but for the errors, I believe that following the Either approach would be simpler. An alternative would be to model all errors (expected or not) as exceptions and use Outcome which is similar to Try.

I think we could make the `Outcome` more flexible, I will back to you when we finish this.

**Pull request closed without merging**
